---
- name: to clean the vm
  shell: rm -rf ./*
- name: to force install
  shell: sudo apt-get -f install
- name: to update ubunty
  shell: sudo apt-get update
- name: to install r package
  shell: sudo apt-get -y install r-base
- name: install git
  shell: sudo apt-get -y install git
- name: to make a directory for cloning the spam detection application
  shell: mkdir "{{applicationpath}}"
- name: to change the directory to have the project folder
  shell: chdir="{{applicationpath}}" git clone "{{kubernetesrepo}}"
- name: to modify the directory permission for installing the packages at site-library
  shell: sudo chmod 777 "{{rpackageinstallation}}"
- name: to change the directory to execute the application
  shell: chdir="{{codepath}}" Rscript spamdetection.r
