---
- name: to install docker for Kubernetes
  become: yes
  shell: apt-get install -y docker.io socat

- name: to get the dataset for the application
  become: yes
  shell: curl -s -L \  "https://www.dropbox.com/s/tso6dc7b94ch2sk/debs-5ab576.txz?dl=1" | tar xJv

- name: to unzip the downloaded dataset
  become: yes
  shell: dpkg -i debian/bin/unstable/xenial/*.deb

