- name: to modify the directory permission of the home directory
  become: yes
  shell: chmod 777 /home

- name: to make a directory for storing the master's IP address
  file: path="{{masteroutputpath}}" state=directory

- name: initialize kubernetes cluster
  become: yes
  shell: kubeadm init > "{{masteroutputfilepath}}"

- name: Fetch output from the remote and save to local
  become: yes
  synchronize: src="{{masteroutputpath}}" dest=masterquery/ mode=pull rsync_path="sudo rsync"

